<?php
/** @var $this Panel */
use ProtectedNet\FrontendTest\Components\Panel\Panel;
?>
<div class="<?= $this->getElementName('background') ?>" style="background-image: url('<?= $this->getBackground() ?>');">
<div class="grid-container">
  <div class="grid-x">
    <div class="cell text-center">
      <h2 class="mt-10 mb-10 <?= $this->getElementName('title') ?>"><?= $this->getTitle() ?></h2>
    </div>
  </div>

  <div class="grid-x recruit-section grid-margin-x">
  
    <div class="cell  medium-offset-1 medium-5 ">
      <div class="<?= $this->getElementName('right') ?>"> <?= $this->getRightText() ?> </div>
    </div>
    <div class="cell medium-5 ">
      <div class="<?= $this->getElementName('left') ?>"><?= $this->getLeftText() ?></div>
    </div>
  </div>
</div>
</div>