<?php
/** @var $this SlideTwo */

use ProtectedNet\FrontendTest\Partials\HeroContent\SlideTwo\SlideTwo;

?>


<div class="<?= $this->getElementName('background-img') ?>" style="background-image: url('<?= $this->getImg('slider-2.jpg') ?>');"></div>


<div class="<?= $this->getElementName('content') ?>">
  <div class="grid-container">
    <div class="grid-x">
      <div class="cell">
        <h1 class="<?= $this->getElementName('title') ?>">Staffing <strong>solutions</strong> for you</h1>
      </div>
    </div>
  </div>
</div>
