<?php
/** @var $this PercentCard */
use ProtectedNet\FrontendTest\Components\PercentCard\PercentCard;
?>

<?php if($this->getIcon()): ?>
  <div class="<?= $this->getElementName('icon') ?>">
    <?= $this->getIcon()->produceSafeHTML() ?>
  </div>
<?php endif; ?>

<div class="<?= $this->getElementName('content') ?>">

  <?php if($this->getTitle()): ?>
    <h4 class="<?= $this->getElementName('title')?>"><?= $this->getTitle() ?></h4>
  <?php endif; ?>

  <?php if($this->getSubtitle()): ?>
    <h5 class="<?= $this->getElementName('subtitle')?>"><?= $this->getSubtitle() ?></h5>
  <?php endif; ?>

  <?php if($this->getDescription()): ?>
    <p class="<?= $this->getElementName('description')?>"><?= $this->getDescription() ?></p>
  <?php endif; ?>

</div>
