<?php
/** @var $this Panel */
use ProtectedNet\FrontendTest\Components\PricePanel\PricePanel;
use ProtectedNet\FrontendTest\Components\Button\Button;
?>
<div>
  <ul class="pricePanel__header-list">
    <li class="pricePanel__header"><?= $this->getHeader() ?></li>
    <li class="pricePanel__price"><?= $this->getPrice() ?></li>
    <li class="pricePanel__desc"><?= $this->getDesc() ?></li>
  </ul>
  <ul class="pricePanel__list"><?= $this->getList() ?></ul>
</div>