<?php
/** @var $this Panel */
use ProtectedNet\FrontendTest\Components\Percent\Percent;
?>
<svg viewBox="0 0 36 36">
  <path class="<?= $this->getElementName('circle-bg')?>"
        d="M18 2.0845
          a 15.9155 15.9155 0 0 1 0 31.831
          a 15.9155 15.9155 0 0 1 0 -31.831"
  />

  <path class="<?= $this->getElementName('circle')?>"
  
    stroke-dasharray="<?= $this->getPercent()?>, 100"
    d="M18 2.0845
      a 15.9155 15.9155 0 0 1 0 31.831
      a 15.9155 15.9155 0 0 1 0 -31.831"
  />
  <text x="18" y="20.35" class="<?= $this->getElementName('percentage')?>"><?= $this->getPercent()?>%</text>
</svg>