<?php
/** @var $this ExamplePartial */

use ProtectedNet\FrontendTest\Partials\ExamplePartial\ExamplePartial;

?>

<h2>Here's an example of a partial</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusamus accusantium aliquid assumenda at atque autem commodi cupiditate debitis dignissimos dolor dolore dolorum earum excepturi, illo itaque laborum maiores minus necessitatibus nihil nisi nostrum odit quaerat, quibusdam quis quos voluptatum!</p>
